main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('sekolah/', views.sekolah, name='sekolah'),
    path('games/', views.games, name='games'),
    path('story1/', views.story1, name="story1"),
    path('watchlist', views.watchlist, name='watchlist')
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

def profile(request):
    return render(request, 'main/profile.html')

def sekolah(request):
    return render(request, 'main/sekolah.html')

def games(request):
    return render(request, 'main/games.html')

def story1(request):
    return render(request, "main/story1.html")

def watchlist(request):
    return render(request, "main/watchlist.html")

main/templates/main/games.html
{% extends 'base.html'%}
{% load static %}

{%block content%}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:home'%}">Halaman Utama</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'main:profile'%}">Data diri</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:sekolah'%}">Riwayat sekolah</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main:games'%}">Games</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:watchlist'%}">Watchlist</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:story1'%}">Story 1</a>
        </li>
      </ul>
    </div>
</nav>
<div class="text-box">
    <h1 class="text-box" style="display: block;">Played Games</h1>
    <ul>
      <li><h2 style="display: block;">Dota 2</h2></li>
      <li><h2 style="display: block;">CSGO</h2></li>
      <li><h2 style="display: block;">Valorant</h2></li>
    </ul>
</div>
{%endblock%}
        

main/templates/main/home.html
{% extends 'base.html'%}
{% load static %}

{%block content%}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main:home'%}">Halaman Utama<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'main:profile'%}">Data diri</a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:sekolah'%}">Riwayat sekolah</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:games'%}">Games</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:watchlist'%}">Watchlist</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:story1'%}">Story 1</a>
        </li>
      </ul>
    </div>
  </nav>
{%endblock%}

main/templates/main/profile.html
{% extends 'base.html'%}
{% load static %}

{%block content%}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:home'%}">Halaman Utama</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'main:profile'%}">Data diri<span class="sr-only">(current)</span></a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:sekolah'%}">Riwayat sekolah</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:games'%}">Games</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:watchlist'%}">Watchlist</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:story1'%}">Story 1</a>
        </li>
      </ul>
    </div>
</nav>
<div class="text-box">
    <h1 class="text-box" style="display: block;">Data diri</h1>
    <p style="display: block; margin: 20px;">Nama     : Hernowo Ari Sutanto <br></p>
    <p style="display: block; margin: 20px;">NPM      : 1906400274 <br></p>
    <p style="display: block; margin: 20px;">Jurusan  : Ilmu Komputer <br></p>
    <p style="display: block; margin: 20px;">Fakultas : Ilmu Komputer <br></p>
    <p style="display: block; margin: 20px;">Angkatan : 2019 <br></p>
</div>
{%endblock%}
        

main/templates/main/sekolah.html
{% extends 'base.html'%}
{% load static %}

{%block content%}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:home'%}">Halaman Utama</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'main:profile'%}">Data diri</a>
          </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main:sekolah'%}">Riwayat sekolah<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:games'%}">Games</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:watchlist'%}">Watchlist</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:story1'%}">Story 1</a>
        </li>
      </ul>
    </div>
</nav>
<div class="text-box">
    <h1 class="text-box" style="display: block;">Riwayat pendidikan</h1>
    <h2 style="display: block; margin-top: 20px;">SD Negeri 20 Mekarjaya</h2>
    <p style="display: block; margin-bottom: 20px;">2007 - 2013</p>
    <h2 style="display: block; margin-top: 20px;">SMP Negeri 4 Depok</h2>    
    <p style="display: block; margin-bottom: 20px;">2013 - 2016</p>
    <h2 style="display: block; margin-top: 20px;">SMA Negeri 1 Depok</h2>
    <p style="display: block; margin-bottom: 20px;">2016 - 2019</p>
</div>
{%endblock%}
        

main/templates/main/story1.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:home'%}">Halaman Utama</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'main:profile'%}">Data diri</a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:sekolah'%}">Riwayat sekolah</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:games'%}">Games</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:watchlist'%}">Watchlist</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main:story1'%}">Story 1<span class="sr-only">(current)</span></a>
        </li>
      </ul>
    </div>
</nav>
<h1>Hello...</h1>
<left><img src="{% static 'img/fotodiri.jpg'%}" width="250" height="300"></left>
<h2>Kenalan Yukk</h2>
<p>Halo, nama saya Hernowo Ari Sutanto, biasa dipanggil Hernowo, Nowo, atau Owo.<br>
Saya saat ini adalah seorang mahasiswa jurusan Ilmu Komputer di Universitas Indonesia.<br>
Hal yang biasa saya lakukan diwaktu luang adalah bermain video game.</p>
<h2>Data Diri Singkat</h2>
<ul>
    <li>Nama     :Hernowo Ari Sutanto</li>
    <li>NPM      :1906400274</li>
    <li>Angkatan :Maung (2019)</li>
</ul>
<h2>Riwayat Pendidikan</h2>
<ul>
    <li>SD Negeri 20 Mekarjaya</li>
    <li>SMP Negeri 4 Depok</li>
    <li>SMA Negeri 1 Depok</li>
</ul>
<h2>Kontak</h2>
<ul>
    <li><a href="https://www.instagram.com/hernowo.arisutanto/" target="_blank">
    <span><img src="{% static 'img/iglogo.png'%}" width="50"></span></a></li>
    <li><a href="https://steamcommunity.com/id/BadBadtzMARU" target="_blank">
    <span><img src="{% static 'img/steamlogo.png'%}" width="50"></span></a></li>
</ul> 
{% endblock %}

main/templates/main/watchlist.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:home'%}">Halaman Utama</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'main:profile'%}">Data diri</a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:sekolah'%}">Riwayat sekolah</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:games'%}">Games</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main:watchlist'%}">Watchlist<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:story1'%}">Story 1</a>
        </li>
      </ul>
    </div>
</nav>
<div class="text-box">
    <h1 class="text-box" style="display: block;">Film/Series yang mau di tonton</h1>
    <ul>
      <li><h3 style="display: block;">Dark</h3>
        <img src="{% static 'img\dark.jpg' %}" style="height: 280px; width: 250px; margin-bottom: 20px;"></li>
      <li><h3 style="display: block;">Blood of Zeus</h3>
        <img src="{% static 'img\Blood-of-Zeus.jpg' %}" style="height: 280px; width: 300px; margin-bottom: 20px;"></li>
      <li><h3 style="display: block;">Dragon Prince</h3>
        <img src="{% static 'img\TheDragonPrince.jpg' %}" style="height: 280px; width: 250px; margin-bottom: 20px;"></li>
    </ul>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hernowo Ari Sutanto</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no"">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    </head>
    <body>
        <div class="box-top">
            <div class="container">
                <img src="{% static 'img\fotodiri.jpg' %}" class="photo-box" style="display:inline-block;">
                <div class="text-box">
                    <h1>Tentangku...</h1>
                    <p>Halo, nama saya Hernowo Ari Sutanto, biasa dipanggil Hernowo, Nowo, atau Owo.<br>
                        Saya saat ini adalah seorang mahasiswa jurusan Ilmu Komputer di Universitas Indonesia.<br>
                        Hal yang biasa saya lakukan diwaktu luang adalah bermain video game.<br>
                    </p>
                </div>
            </div>
        </div>
  {% block content %}
  {% endblock content %}
  <div class="box-bot">
    <h1 class="text-box" style="color: white;"> Kontak </h1>
    <div class="box-kontak">
        <div class="box-logo">
            <a href="https://www.instagram.com/hernowo.arisutanto/" target="_blank">
            <span><img src="{% static 'img\iglogo.png'%}" width="50"></span> hernowo.arisutanto</a>
        </div>
        <div class="box-logo-steam">
            <a href="https://steamcommunity.com/id/BadBadtzMARU" target="_blank">
            <span><img src="{% static 'img\steamlogo.png'%}" width="50"></span> https://steamcommunity.com/id/BadBadtzMARU</a>
        <div class="box-logo">
            <a href="https://www.facebook.com/hernowo.arisutanto/" target="_blank">
            <span><img src="{% static 'img\facebook-logo.png'%}" width="35" height="50">  Hernowo Ari Sutanto</span></a>
        </div>
        </div>
    </div>
</div>
</body>
</html>